version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: file_metadata_storage
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: file_metadata_storage
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 123123
    ports:
      - "8000:8000"

volumes:
  pgdata:
